services:
  - type: web
    name: healthcare-chatbot-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: USE_REDIS
        value: "false"
      - key: WHATSAPP_PROVIDER
        value: AUTOBOTCHAT
      - key: AUTOBOTCHAT_USERNAME
        value: Digify_soft
      - key: META_VERIFY_TOKEN
        value: automatex_copilot_token


